
# NOTE: `embedding_size` and `logit_size` are external parameters

# NOTE: The following section will be embedded in `default_config.yml` in `tf-metric-learning` repo
#       and with the key: `evaluator`.

# database: Zeus | DatasetBackbone | None
database:

# upper-bound of the evaluation instances
container_size: 50000

chosen_evaluations:
    - CheckoutEvaluation
#    - RankingEvaluation
#    - FacenetEvaluation

# Configurations for evaluator:
evaluation_options:
    # Implemented Evaluations
    FacenetEvaluation:
        sampling:
            # random_sample | amount_weighted | amount_inverse_weighted
            class_sample_method: random_sample
            num_of_pairs: 1000
            num_of_instance_per_class: 1
            ratio_of_class: 0.1

        # these will be checked in FacenetEvaluation
        metric:
            accuracy:            true
            validation_rate:     true
            false_accept_rate:   false
            true_positive_rate:  true
            false_positive_rate: false

        distance_measure:
            function:
                - euclidean
            threshold:
                start: 1.0
                end: 1.5
                step: 0.25
        attribute: # not support

        option:
            path_pairlist: # not done

    RankingEvaluation:
        sampling:
            class_sample_method: uniform
            instance_sample_method: uniform
            num_of_db_instance: 10
            num_of_query_class: 100
            num_of_query_instance_per_class: 1
            maximum_of_sampled_data: 10000

        metric:
            # top_1_hit is defaults
            top_k_hit_accuracy:
                - 1
                - 5
            mAP: true

        distance_measure:
            function:
            threshold:

        attribute: # not support

        option:
            path_database: # not done
            seen_dataset: # not done
            unseen_dataset: # not done

    # The evaluation supports only offline
    CheckoutEvaluation:
        sampling:
            class_sample_method: all_class
            instance_sample_method: all_instance
            num_of_db_instance: 10
            num_of_query_class: 50
            num_of_query_instance_per_class: 1
            maximum_of_sampled_data: 10000

        metric:
            # top_1_hit is defaults
            top_k_hit_accuracy:
                - 1
                - 5
            mAP: true

        attribute:
            - seen_to_seen
            - unseen_to_unseen
            - seen_to_total
            - unseen_to_total

        option:
            num_of_seen_query_class: 100
            num_of_seen_db_instance: 10
            num_of_seen_query_instance_per_class: 1
            num_of_unseen_query_class: 100
            num_of_unseen_db_instance: 1
            num_of_unseen_query_instance_per_class: 1
            num_of_total_db_instance: 200
            seen_unique_ids: data/seen_unique_ids_gp1444.json
            unseen_unique_ids: data/unseen_unique_ids_gp1444.json
            label_map: data/labelmap_1933.json

# OPTIONS OF EACH ITEMS