# Configuration used for metric-learning evaluator.

# database: Zeus | DatasetBackbone | None
database:
#database: DatasetBackbone

# upper-bound of the evaluation images
container_size: 30000

# tf-metric-learning config
embedding_size: 2048
# Close the logit option.
logit_size: 0

# list of evaluations
evaluation:
  # per evaluation config
  # NOTE:
  #    - per_eval_config should be dict rather than list.
    FacenetEvaluation:
        # path to the list of pairs
        option:
            path_pairlist:
        metric:
            distance_threshold: # start, end, step
                - 0.5
                - 0.75
                - 1.0
                - 1.25
                - 1.5
                - 2.0
            pair_sampling:
                ratio_of_class: 0.1
                ratio_of_image_per_class: 0.1
                class_sample_method: random_sample

        attribute:

# template of per evaluation config
#   MockEvaluation:
#       system:
#           path:
#       metric:
#           metric_type:
#               -
#               - list
#           metric_type: int
#       attribute:
#            - attribute_type_1
#            - attribute_type_2