# Configuration used for metric-learning evaluator.

# database of attributes
database: DatasetBackbone

# list of evaluations
evaluation:
  # per evaluation config
  # NOTE:
  #    - per_eval_config should be dict rather than list.
    mock:
        Attr:
            - Color
    ranking:
        Attr:
            - Color
            - Shape
    classification:
        Top_k: 5

# upper-bound of the evaluation images
container_size: 10000

# tf-metric-learning config
embedding_size: 2048

logit_size: 1400