# CONFIGURATION HANDLES SOME STATIC INFORMATION

labelmap_path: misc/labelmap_1933.json

detector_settings:
  num_classes: 1
  model_path: /home/trained_models/ssd_fpn_0.50.7/frozen_inference_graph.pb
  labelmap_path: /home/cworkspace/checkout-system/se7en_models/det_se7en748_frcnn_incepv2_synth_20k_real_10k_v0/agnostic_labelmap.pbtxt

extractor_settings:
  image_size: 224
  model_path: /home/trained_models/bread-triplet-is224-es256-factor0.25-margin0.5
  database_path: /home/cworkspace/bakery/features/triplet-is224-es256-factor0.25-margin0.5/features_fukuoka_marumoto_singles