# CONFIGURATION HANDLES SOME STATIC INFORMATION

labelmap_path: misc/labelmap_1933.json
embedding_container_capacity: 100000

detector_settings:
  num_classes: 1
  model_path: /home/trained_models/ssd_fpn_0.50.7/frozen_inference_graph.pb
  labelmap_path: misc/agnostic_labelmap.pbtxt

extractor_settings:
  image_size: 224
  embedding_size: 2048
  model_path: /home/trained_models/bread-triplet-is224-es256-factor0.25-margin0.5
  # label `unknown_instance` if databse is not given
  database_path: /home/cworkspace/bakery/features/triplet-is224-es256-factor0.25-margin0.5/features_fukuoka_marumoto_singles